[package]
name = "sparky"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.1"
winit = { version = "0.29.15" }

# OpenGL dependencies
gl = "0.14.0"
glutin = "0.31.3"
glutin-winit = "0.4.2"

# Required for glutin
raw-window-handle = "0.5"
rand = "0.9.2"
tray-icon = "0.21.1"
